import { NextResponse } from 'next/server'

const inspirations = [
  "In the style of Helmut Newton: Leica S2 medium format, Summicron 90mm f/2 lens, high-contrast black and white, low angle at +20°, slight Dutch tilt of 10°. Statuesque 5'11\" woman, sharp cheekbones, with ((short slicked-back blonde hair)), commanding gaze. Wearing tailored Yves Saint Laurent tuxedo, no accessories, minimalist makeup emphasizing bold lips (captured in black and white). Subject stands confidently with hand on hip, body angled at 45° to camera. Lighting setup includes strong key light from 45° camera left, creating deep shadows. Background is a dimly lit Parisian street at night. Post-processing involves high contrast, enhanced grain, deep blacks, capturing Newton's provocative style.",
  "In the style of Vivian Maier: Rolleiflex 3.5F twin-lens reflex camera, 75mm f/3.5 lens, black and white square format, natural daylight. Thoughtful middle-aged man, glasses perched on nose, with ((slightly unkempt curly brown hair under a flat cap)), reflective expression. Captured candidly on bustling city sidewalk, subject occupies 30% of frame, background includes urban architecture and passersby. Camera held at waist level for perspective, eye-level angle (0°). Subject unaware of camera, providing authentic street scene. Post-processing includes moderate contrast, preserved mid-tones, subtle grain characteristic of Maier's style.",
  "In the style of Steve McCurry: Nikon D850, 85mm f/1.4 lens, vibrant Kodachrome color palette, natural golden hour lighting. Young woman with striking green eyes, with ((long, flowing auburn hair wrapped in a patterned scarf)), intense gaze. Captured at eye level (0°), close-up framing, subject occupies 70% of frame. Background is softly blurred, hints of marketplace environment at f/2.8. Subject positioned 6 feet from camera, face turned slightly at 15°, direct eye contact. Post-processing enhances rich colors and contrasts, preserving fine details, reflecting McCurry's iconic style.",
  "In the style of Mary Ellen Mark: Hasselblad 500CM, 80mm f/2.8 lens, black and white film, natural diffused light. Elderly woman, weathered face, with ((long grey hair braided over shoulder)), eyes reflecting wisdom. Captured at eye level (0°), 3/4 facial view at 45°, shoulders relaxed. Subject seated outside rustic wooden house, hands clasped in lap. Background includes subtle elements of rural life, blurred at f/4. Subject occupies 60% of frame. Post-processing includes rich tonal range, emphasizing textures and details true to Mark's empathetic style.",
  "In the style of Richard Avedon: Large format 8x10 camera, 300mm lens, studio with seamless white background, soft even lighting. Elegant woman, poised posture, with ((sleek black bob hairstyle)), expressive eyes. Captured at eye level (0°), subject facing directly into camera, minimalistic composition. Wearing classic black Givenchy dress, pearl earrings, minimal makeup focusing on bold red lips. Subject positioned 5 feet from camera, aperture at f/16 for maximum depth of field. Lighting includes large softbox at 45° angle, producing even illumination. Post-processing emphasizes sharpness and high contrast, characteristic of Avedon's iconic portraits.",
  "In the style of Steven Meisel: Mamiya RZ67 Pro II, 110mm f/2.8 lens, studio lighting with large octabox key light, high angle at -25°. Fashion model, 5'10\" with slender frame, with ((long wavy red hair styled in loose curls)), confident expression. Wearing avant-garde Prada ensemble with bold patterns, accessorized with chunky jewelry. Pose includes one hand on hip, body angled at 30° to camera, chin slightly lifted. Subject occupies 80% of frame, background is minimalist light gray. Aperture at f/8 for crisp focus, lighting ratio 2:1 creating subtle depth. Post-processing includes vibrant color grading, maintaining skin tones, reflective of Meisels polished style.",
  "In the style of Ansel Adams: Large format view camera, 90mm wide-angle lens, black and white with high contrast, deep depth of field at f/22. Lone hiker standing on cliff edge overlooking Yosemite Valley, back turned to camera, with ((short messy dark hair under wide-brimmed hat)), sturdy build. Captured from slightly below eye level (+10°), subject occupies 20% of frame. Majestic landscape includes dramatic clouds, towering mountains, vast forest. Natural lighting during golden hour enhances textures. Post-processing sharpens details, emphasizes contrast, capturing Adams' zone system technique.",
  "In the style of Cindy Sherman: Canon EOS 5D Mark III, 24-70mm f/2.8 lens, studio lighting with dramatic shadows. Self-portrait of woman in costume, with ((disheveled blonde wig styled haphazardly)), exaggerated makeup. Captured at eye level (0°), frontal pose, subject gazes blankly into camera. Wearing vintage 1950s housewife attire, apron stained, holding cracked teacup. Background is staged domestic interior, slightly disheveled. Subject positioned 8 feet from camera, aperture at f/5.6. Lighting includes key light from above creating harsh shadows. Post-processing enhances colors and textures, slight vignette, reflective of Sherman's commentary on identity.",
  "In the style of Henri Cartier-Bresson: Leica M3, 50mm f/2 lens, black and white film, natural light. Young couple holding hands, with ((both have short curly hair)), expressions of joy. Captured candidly on Parisian street, decisive moment as they step off curb, motion blur in background. Camera at eye level (0°), subjects occupy 50% of frame, leading lines from street guide viewer's eye. Aperture at f/8 for moderate depth of field. Post-processing maintains mid-tones, subtle contrast, grainy texture characteristic of Cartier-Bresson's work.",
  "In the style of Annie Leibovitz: Hasselblad H6D-100c, 80mm f/2.8 lens, dramatic studio lighting with softboxes and grids, high angle at -15°. Celebrated actor seated on ornate chair, with ((graying hair slicked back)), thoughtful expression. Wearing bespoke three-piece suit by Tom Ford, pocket watch chain visible, minimal accessories. Subjects body angled at 30° to camera, face turned back toward lens. Background includes rich, textured curtains, evoking theatrical setting. Subject positioned 10 feet from camera, aperture at f/11 for full focus. Post-processing emphasizes rich colors, deep shadows, subtle vignette, embodying Leibovitz's dramatic portrait style.",
  "In the style of Edward Weston: Large format 8x10 camera, 240mm lens, black and white film, natural soft light. Study of human form, adult woman, with ((long flowing dark hair arranged over shoulders)), posed artistically. Captured at eye level (0°), abstract composition focusing on curves and lines. Subject posed reclining, body angled at 45° from camera, limbs creating geometric shapes. Background is simple neutral fabric, no distractions. Aperture at f/16 for deep depth of field, emphasis on form rather than identity (face not visible). Post-processing includes smooth tonal gradations, high contrast, capturing Weston's approach to form and texture.",
  "In the style of Peter Lindbergh: Hasselblad X2D 100C, XCD 90mm f/2.5 lens at f/4, natural light with silver reflector. Athletic surfer physique, sun-kissed skin, with ((tousled beach waves styled naturally)), strong jawline, weathered features. Worn denim jacket, white linen shirt, leather wrap bracelet, natural skin texture. Shot at golden hour on rocky beach, dramatic clouds, sea spray atmosphere. Low angle (+15°) composition, subject at 30° to camera, characteristic black and white conversion with enhanced texture detail.",
  "In the style of Tim Walker: Canon EOS R5, RF 85mm f/1.2L at f/2.8, elaborate studio lighting setup with colored gels. Ethereal female figure, porcelain skin, with ((flowing red hair in romantic waves)), delicate features. Avant-garde Alexander McQueen gown, surreal butterfly headpiece, theatrical makeup. Whimsical set design with oversized books and floating teacups. Shot from slight high angle (-10°), dreamy soft focus, signature pastel color grading with fantasy elements.",
  "In the style of Steve McCurry: Nikon Z9, NIKKOR Z 70-200mm f/2.8 at 135mm, natural light with gold reflector. Elderly monk, weathered face, with ((traditional Buddhist monk shaved head)), deep wisdom lines. Traditional saffron robes, prayer beads, authentic religious artifacts. Ancient temple interior, shaft of light through window, incense smoke atmosphere. Eye-level composition, subject at 45° angle, McCurrys signature Kodachrome color processing with rich saturated tones.",
  "In the style of Richard Avedon: Phase One IQ4, Schneider 120mm f/4 at f/8, precision studio strobe array. Ballet dancer physique, elongated limbs, with ((sleek high bun hairstyle)), graceful neck. Minimal black leotard, pointe shoes, no accessories. Classic white seamless background, dynamic leap capture. Shot from low angle (+20°), tack-sharp focus, high-contrast black and white conversion with perfect tonal range.",
  "In the style of Annie Leibovitz: Sony A1, 24-70mm f/2.8 GM II at 50mm, complex lighting with colored gels. Tech CEO persona, confident stance, with ((modern textured crop)), strong features. Casual luxury attire, minimal jewelry, natural makeup. Modern office environment, city skyline background, blue hour ambient light. Dutch angle (10°), environmental portrait composition, signature dramatic lighting with cinematic color grade.",
  "In the style of Helmut Newton: Leica M11 Monochrom, 50mm Noctilux f/0.95 at f/2, natural window light. Powerful female executive, statuesque build, with ((sharp platinum bob cut)), strong bone structure. Power suit with stilettos, minimal jewelry, bold red lip. Luxury hotel suite setting, mirror reflections, modernist furniture. Low angle (+25°), provocative pose, high-contrast black and white with deep shadows.",
  "In the style of Irving Penn: Hasselblad 907X, 90mm f/3.2 at f/5.6, controlled daylight studio setup. Indigenous elder, dignified presence, with ((traditional tribal headdress)), characterized face. Authentic tribal attire, ceremonial jewelry, body paint details. Simple backdrop, corner composition. Eye-level shot, perfect symmetry, Penn's signature soft contrast with rich middle tones.",
  "In the style of Paolo Roversi: Phase One XT, 80mm f/2.8 at f/4, soft diffused studio light. Ethereal model physique, translucent skin, with ((romantic disheveled updo)), delicate features. Vintage couture gown, antique lace details, pearl accessories. Painterly backdrop, atmospheric haze. Shot through textured glass, signature soft focus, Roversi’s characteristic muted color palette.",
  "In the style of Albert Watson: Canon EOS R3, RF 50mm f/1.2 at f/1.8, dramatic single-source lighting. Rock musician persona, lean build, with ((messy shoulder-length rocker style)), intense gaze. Leather jacket, vintage band shirt, silver jewelry. Industrial location, smoke effects, dramatic shadows. Shot from below (+30°), sharp focus on eyes, Watson’s signature high-contrast processing.",
  "In the style of Mario Sorrenti: Fujifilm GFX 100S, GF 110mm f/2 at f/2.8, natural light with minimal fill. Fashion model physique, angular features, with ((wet-look slicked back style)), sharp cheekbones. Designer swimwear, minimal accessories, dewy skin. Oceanfront location, breaking waves, spray atmosphere. Shot at water level, dynamic movement capture, Sorrenti’s signature raw, organic color treatment.",
]

export async function GET() {
  const randomPrompt = inspirations[Math.floor(Math.random() * inspirations.length)]
  return NextResponse.json({ prompt: randomPrompt })
}
